#!/bin/bash

while getopts ":m" opt; do
  case $opt in
    m)
      move=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

workspace=$(i3-msg -t get_workspaces | jq -r '.[] | .name' | dmenu)

if [ "$move" == "true" ]
then
	i3-msg move container to workspace "${workspace}"
else
	i3-msg workspace "${workspace}"
fi

